name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --global user.email "saadtoorx@gmail.com"
          git config --global user.name "saadtoorx"

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote remove hf || true
          git remote add hf https://saadtoorx:${HF_TOKEN}@huggingface.co/spaces/saadtoorx/car-price-predictor-using-rf
          git push hf main --force
