name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --global user.email "saadtoorx@gmail.com"
          git config --global user.name "saadtoorx"

      - name: Push to Hugging Face Spaces
        run: |
          git remote add hf https://saadtoorx:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/saadtoorx/car-price-predictor-using-rf
          git push hf HEAD:main --force
